### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

### ISSUE THREAD

**Issue by anthonyyuan** [Xinyu-Yi/TransPose#8]
Traceback (most recent call last):
  File "/home/anthony/Downloads/TransPose-main/example.py", line 15, in <module>
    net = TransPoseNet().to(device)
  File "/home/anthony/Downloads/TransPose-main/net.py", line 47, in __init__
    m = art.ParametricModel(paths.smpl_file)
  File "/home/anthony/Downloads/TransPose-main/articulate/model.py", line 30, in __init__
    self._J_regressor = torch.from_numpy(data['J_regressor'].toarray()).float().to(device)
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

**Comment by Xinyu-Yi** [comment]
Hi. Please check if you download the correct smpl model file according to the readme.
